# Generated by Django 3.1 on 2020-12-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationUser',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ApplicationUser',
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(default='unknown', max_length=300)),
                ('long', models.FloatField(default=0.0)),
                ('lat', models.FloatField(default=0.0)),
                ('start_hour', models.CharField(max_length=50)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to='events.applicationuser')),
            ],
            options={
                'db_table': 'UserEvent',
            },
        ),
    ]
